### ISSUE TITLE
What is the use of the rraes package and why it it not used for f1

### ISSUE THREAD

**Issue by advanderveer** [kargakis/chiapos#21]
I'm studying the Chia proof of space construction and your implementation is a lifesaver. But I don't fully understand why the rraes package exists. Is it a custom aes implementation that you wrote, why is that necessary? And why is it not used for F1? Maybe I'm missing something in the chia docs. 

Thank you,

**Comment by kargakis** [comment]
The first version of the Chia PoSpace algorithm used AES and a reduced rounds version of it (RRAES) to generate the proofs. They have switched to ChaCha8 and BLAKE3 since I finished my PoC.

https://github.com/Chia-Network/chiapos/commit/0f8eee893ef73a6668df09e4106ebc4bfa45d721#diff-e827098c38e8ebb0816617faf193c521cc59a453d7bb996f870a6468871c3431

**Comment by advanderveer** [comment]
Ah that makes sense, great! thank you!
